variables:
  APP_VERSION: v0.$CI_PIPELINE_IID

stages:
  - build
  - deploy

.build_job_template:
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

include:
  - local: build-stage.yml
  - local: deploy-stage.yml

