variables:
  APP_VERSION: v0.$CI_PIPELINE_IID

stages:
  - build
  - deploy
  - rollback

.build_job_template:
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - APP_VERSION=v0.$CI_PIPELINE_IID
    - echo "TAG $APP_VERSION"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$APP_VERSION
    - mkdir dist
  tags:
    - docker-runner
  artifacts:
    paths:
      - dist/


.deploy_template:
  script:
    - echo "Deploying application..."
    - echo "Deploying version $APP_VERSION"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker stop $CI_PROJECT_NAME || true
    - docker rm $CI_PROJECT_NAME || true
    - docker run -d -p 80:80 --name $CI_PROJECT_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:$APP_VERSION
    - docker push $CI_REGISTRY_IMAGE:$APP_VERSION
  tags:
    - docker-runner
  after_script:
    - 'if [ "$CI_JOB_STATUS" == "success" ]; then curl -X POST -H "Content-type: application/json" --data "{\"content\":\"Deployment successful! Version: $CI_COMMIT_REF_NAME\"}" $DISCORD_WEBHOOK; fi'
    - 'if [ "$CI_JOB_STATUS" == "failed" ]; then curl -X POST -H "Content-type: application/json" --data "{\"content\":\"Deployment failed! Version: $CI_COMMIT_REF_NAME\"}" $DISCORD_WEBHOOK; fi'

.rollback_template:
  script:
    - echo "Rolling back to the previous version..."
    - ALL_TAGS=($(docker image ls --format '{{.Repository}}:{{.Tag}}' | grep $CI_REGISTRY_IMAGE))
    - SORTED_TAGS=($(echo "${ALL_TAGS[@]}" | tr ' ' '\n' | sort -V -r))
    - PREVIOUS_VERSION=${SORTED_TAGS[1]}
    - echo "TAG APP_VERSION $APP_VERSION"
    - echo "TAG PREVIOUS_VERSION $PREVIOUS_VERSION"
    - docker stop $CI_PROJECT_NAME || true
    - docker rm $CI_PROJECT_NAME || true
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $PREVIOUS_VERSION || true
    - docker run -d -p 80:80 --name $CI_PROJECT_NAME $PREVIOUS_VERSION
    - 'curl -X POST -H "Content-type: application/json" --data "{\"content\":\"Rollback successful! Version: $PREVIOUS_VERSION\"}" $DISCORD_WEBHOOK; '
  tags:
    - docker-runner

include:
  - local: build-stage.yml
  - local: deploy-stage.yml
  - local: rollback-stage.yml
